//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by sinstar2.rc
//
#define IDC_SKIN_EDIT                   4
#define IDI_FLAG                        101
#define IDC_MYHAND                      104
#define IDR_SYSMENU                     105
#define IDB_COMPICON                    107
#define IDB_BITMAP1                     108
#define IDD_PROP_ABOUT                  109
#define IDD_PROP_CUSTOM                 110
#define IDD_PROP_ASSOCIATE              111
#define IDD_PROP_OTHER                  112
#define IDD_PROP_HOTKEY                 113
#define IDD_UDICT_INPUT                 114
#define IDD_PROP_CANDMODE               115
#define IDI_SETTINGS                    116
#define IDR_FADESTEPS                   118
#define IDD_PROP_PLUGIN                 119
#define IDD_SKIN_MANAGER                121
#define IDD_PROP_WNDEFFECT              122
#define IDC_ASTSENT                     1001
#define IDC_ASTNULL                     1003
#define IDC_ASTCAND                     1004
#define IDC_ASTENGLISH                  1005
#define IDC_PHRASEREMIND                1006
#define IDC_SW_LSHIFT                   1006
#define IDC_SW_RSHIFT                   1007
#define IDC_SW_DISABLE                  1008
#define IDC_SERVER                      1010
#define IDC_VER_SVR                     1010
#define IDC_VER_IME                     1011
#define IDC_TP_LCTRL                    1012
#define IDC_TP_RCTRL                    1013
#define IDC_HOMESITE                    1014
#define IDC_23CANDKEY                   1017
#define IDC_FORECAST_DISABLE            1020
#define IDC_FORECAST_ALWAYS             1021
#define IDC_FORECAST_NOCAND             1022
#define IDC_CONFIGHELP                  1023
#define IDC_LINEKEY1                    1024
#define IDC_LINEKEY2                    1025
#define IDC_LINEKEY3                    1026
#define IDC_LINEKEY4                    1027
#define IDC_LINEKEY5                    1028
#define IDC_LINEKEY6                    1029
#define IDC_BTN_PHONTICCOLOR            1031
#define IDC_CR_PNTC                     1034
#define IDC_PHONTIC_LEFT                1035
#define IDC_PHONTIC_RIGHT               1036
#define IDC_SLIDER_TRANSPARENT          1037
#define IDC_TRANS_DEGREE                1038
#define IDC_PAGECANDS                   1039
#define IDC_SPIN_PAGECANDS              1040
#define IDC_WILD_FIRST                  1041
#define IDC_FAST_UMODE                  1041
#define IDC_SHOWTIP                     1042
#define IDC_SPELL_BLUR                  1044
#define IDC_AUTOMATCH                   1045
#define IDC_USERDEF                     1046
#define IDC_2CANDKEY                    1047
#define IDC_SYMBOLMAP                   1047
#define IDC_3CANDKEY                    1048
#define IDC_EMAIL                       1048
#define IDC_TURNPAGE_UP                 1049
#define IDC_CHARSET_GB                  1050
#define IDC_CHARSET_GBK                 1051
#define IDC_TTS_INPUT                   1052
#define IDC_TURNPAGE_DOWN               1052
#define IDC_ENTER_CLEAR                 1052
#define IDC_BLENDUD                     1053
#define IDC_MAXCODE_INPUT               1054
#define IDC_AUTO_INPUT                  1054
#define IDC_MAXCODE_INPUT2              1055
#define IDC_HOTKEY_2CAND                1055
#define IDC_ENTER_INPUT                 1055
#define IDC_HOTKEY_3CAND                1056
#define IDC_PYCAND_PHRASEFIRST          1056
#define IDC_HOTKEY_CAND_PAGEUP          1057
#define IDC_SOUND_ALERT                 1057
#define IDC_HOTKEY_CAND_PAGEDOWN        1058
#define IDC_AUTOHIDEGBK                 1058
#define IDC_HOTKEY_SWITCH_MODE          1059
#define IDC_DISABLEFNKEY                1059
#define IDC_HOTKEY_SWITCH_EN            1060
#define IDC_AUTODOT                     1060
#define IDC_HOTKEY_QUERY                1061
#define IDC_RATE_DISABLE                1061
#define IDC_HOTKEY_MAKEWORD             1062
#define IDC_RATE_AUTO                   1062
#define IDC_HOTKEY_SHOWROOT             1063
#define IDC_RATE_QUICK                  1063
#define IDC_AUTOPROMPT                  1064
#define IDC_HOTKEY_UDICT                1064
#define IDC_HOTKEY_HIDESTATUS           1065
#define IDC_FASTKEY_UMODE               1066
#define IDC_FASTKEY_SENTENCE            1067
#define IDC_EDIT_KEY                    1067
#define IDC_LIST_KEY                    1068
#define IDC_CONVERT                     1069
#define IDC_COPY                        1070
#define IDC_DELWORD_DISABLE             1071
#define IDC_WEB_HEADER                  1072
#define IDC_TRANS_STATUS                1073
#define IDC_SPIN_TRANS_STATUS           1075
#define IDC_TRANS_INPUT                 1076
#define IDC_SPIN_TRANS_INPUT            1077
#define IDC_RECORD_LOG                  1078
#define IDC_CANDSEL_NONUM               1079
#define IDC_HOTKEY_QUERYDICT            1080
#define IDC_GBK_HIDE                    1081
#define IDC_GBK_SHOWI                   1082
#define IDC_GBK_SHOWA                   1083
#define IDC_MOUSEFOLLOW                 1083
#define IDC_ANIMATEWND                  1084
#define IDC_FADE_STEPS                  1086
#define IDC_FADE_STEP_MENU              1087
#define IDC_LIST_PLUGIN                 1088
#define IDC_DESCRIPT                    1089
#define IDC_VERSION                     1090
#define IDC_NAME                        1091
#define IDC_ONLYSIMPLECODE              1091
#define IDC_AUTOEXIT                    1092
#define IDC_LIST_SKIN                   1093
#define IDC_SKIN_DIR                    1094
#define IDC_SKIN_DEL                    1095
#define IDC_SKIN_WEB                    1096
#define IDC_SKIN_REFRESH                1097
#define IDC_TP_KEY                      1099
#define IDC_SHADE_INPUT                 1100
#define IDC_SHADE_STATUS                1101
#define IDC_SOUND_DISABLE               1102
#define IDC_SOUND_WAV                   1103
#define IDC_SOUND_BEEP                  1104
#define IDM_HELP                        40001
#define IDM_CONFIG                      40003
#define IDM_OPENSERVER                  40005
#define IDM_KEYMAP                      40006
#define ID_MAKEPHRASE                   40009
#define IDM_IMCHANGE                    40011
#define IDM_MAKEPHRASE                  40012
#define IDM_QUERYCOMP                   40014
#define IDM_SPEED                       40015
#define IDM_HIDESTATUS                  40016
#define IDM_MOUSEFOLLOW                 40017
#define IDM_FS_NOFADE                   40032
#define IDM_FS_FAST                     40033
#define IDM_FS_MIDDLE                   40034
#define IDM_FS_SLOW                     40035
#define IDM_FS_SLOWEST                  40036
#define IDM_SKIN_SET                    40038
#define ID_BLEND_SP_CE2                 40041
#define ID_BLEND_SP_CE3                 40042
#define ID_BLEND_SP_CA4                 40043
#define ID_BLEND_USERDEF                40044
#define ID_SKIN_WEB                     40045
#define ID_BLEND_SP_WORD                40046
#define IDM_INPUTBIG5                   40047
#define ID_BATCH_SETTINGS1              40060
#define ID_BATCH_SETTINGS20             40079
#define ID_UDICT_INPUT                  40080
#define ID_UDICT_CLOSE                  40081
#define ID_UDICT_1                      40082
#define ID_UDICT_20                     40101
#define ID_SPCHAR_FIRST                 40120
#define ID_SPCHAR_END                   40139
#define ID_SKIN_VERTICAL                40189
#define ID_SKIN_MANAGER                 40190
#define ID_SKIN_RANDOM                  40200
#define ID_SKIN_BEGIN                   40201
#define ID_SKIN_END                     40230
#define ID_COMP_FIRST                   40300
#define ID_COMP_END                     40349
#define IDM_SVR_TRAY                    40401
#define IDM_SVR_PAGE1                   40402
#define IDM_SVR_PAGE50                  40451

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        125
#define _APS_NEXT_COMMAND_VALUE         40055
#define _APS_NEXT_CONTROL_VALUE         1103
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
